repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0  # pick a git hash / tag to point to
    hooks:
    -   id: flake8
        args: ['--config=.flake8']
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: 'v5.10.1'  # Use the revision sha / tag you want to point at
    hooks:
    -   id: isort
        additional_dependencies: ["isort==5.10.1"]
        # In this example, the additional_dependencies field explicitly sets the isort
        # version to 5.11.2. Ensure that the version specified here matches the version
        # you have in your pyproject.toml.
        # By including the additional_dependencies field, the isort hook will use the
        # isort version specified in your project's dependencies, respecting your
        # pyproject.toml configuration.
